added archive package, added go.sum file, fixed error handling
gspivey/drayage pull request #9
Opened 2019-07-22 16:49 UTC by owilliams99

Still looking for a way tar the file without the additional directories

2019-07-23 02:43 UTC, gspivey requested changes
Please address two of my comments. Overall this looks good. I expect `WriteToTar` to change soon. its going to need some parameters to change how it operates. For example how would you only tar a specific volume? You don't need to update that part now but something to think about.

2019-07-23 02:43 UTC, gspivey commented on archive/tarfile.go
> +			return fmt.Errorf("can't open %v (did you use sudo?)", vol.Name)
On your return "chain" the errors like in the example below:

```go
if err := dec.Decode(&val); err != nil {
    if serr, ok := err.(*json.SyntaxError); ok {
        line, col := findLine(f, serr.Offset)
        return fmt.Errorf("%s:%d:%d: %v", f.Name(), line, col, err)
    }
    return err
}
```

Something like this should work:

```go 
return fmt.Errorf("can't open %v (did you use sudo?) : %v ", vol.Name, err)
```

2019-07-23 02:43 UTC, gspivey commented on archive/tarfile.go
> +	V "github.com/gspivey/drayage/volume"
the word `volume` does not seem to be used. Why alias it to V?

2019-07-23 02:43 UTC, gspivey commented on archive/tarfile.go
> +		var fileWriter io.WriteCloser = tarfile
Nothing to address: Fascinating. You passed each type of iowriter is acting as a "filter".cool

2019-07-23 02:43 UTC, gspivey commented on archive/tarfile_test.go
> +func TestWriteToTar(t *testing.T) {
Nothing to address: We have been using the test capability just to run our code from our package. We should start writing some actual unit tests to go with the code

2019-07-23 02:44 UTC, gspivey commented
> Still looking for a way tar the file without the additional directories

Don't worry about this part for now. There are enough other things we can work on before worrying about this. Write an issue for this problem and we can address it later.

2019-07-25 16:41 UTC, owilliams99 commented
I have updated the WriteToTar function and have gotten the tar command working with drayage

2019-07-25 18:44 UTC, gspivey approved these changes

2019-07-25 18:45 UTC, merged